name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Set this to your default branch
  workflow_dispatch:    # Allows manual triggering

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use your preferred Node.js version
          cache: 'npm'      # Change to 'yarn' if using yarn

      - name: Install dependencies
        run: npm ci         # Use 'yarn install --frozen-lockfile' if using yarn

      - name: Build
        run: npm run build  # Use 'yarn build' if using yarn

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist      # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to